-- Read-only verification for 055_normalize_g6_static_readability.sql
-- Run only after the guarded write migration reports success.
WITH expected (
  id, lesson_number, question_type, before_question_text, before_options,
  correct_answer, before_explanation, after_question_text, after_options,
  after_explanation
) AS (
  VALUES
    ('2acb712d-db45-457c-9089-a7869a416460'::uuid, 'M6.EE.1.3', 'multiple_choice', 'In the expression 5x^2 + 3x - 7, what is the coefficient of x ', '[{"key":"A","text":"5"},{"key":"B","text":"2"},{"key":"C","text":"3"},{"key":"D","text":"-7"}]'::jsonb, 'C', 'The coefficient is the number multiplied by the variable. In 3x, the coefficient is 3.', 'In the expression 5x^2 + 3x - 7, what is the coefficient of x?', '[{"key":"A","text":"5"},{"key":"B","text":"2"},{"key":"C","text":"3"},{"key":"D","text":"-7"}]'::jsonb, 'The coefficient is the number multiplied by the variable. In 3x, the coefficient is 3.'),
    ('68c88803-4aa2-46a6-b979-ec3ec2fd8579'::uuid, 'M6.EE.1.3', 'multiple_choice', 'In the expression 4y^3, what is the exponent ', '[{"key":"A","text":"4"},{"key":"B","text":"y"},{"key":"C","text":"3"},{"key":"D","text":"4y"}]'::jsonb, 'C', 'The exponent tells how many times the base is multiplied by itself. In y^3, the exponent is 3.', 'In the expression 4y^3, what is the exponent?', '[{"key":"A","text":"4"},{"key":"B","text":"y"},{"key":"C","text":"3"},{"key":"D","text":"4y"}]'::jsonb, 'The exponent tells how many times the base is multiplied by itself. In y^3, the exponent is 3.'),
    ('d7da2c15-29df-4f94-9fe9-adac8f4b0ad8'::uuid, 'M6.EE.1.3', 'multiple_choice', 'Which of the following are like terms ', '[{"key":"A","text":"3x and 3y"},{"key":"B","text":"5x^2 and 5x"},{"key":"C","text":"4ab and 7ab"},{"key":"D","text":"2x and 2x^2"}]'::jsonb, 'C', 'Like terms have identical variable parts. 4ab and 7ab both have the variable ab.', 'Which of the following are like terms?', '[{"key":"A","text":"3x and 3y"},{"key":"B","text":"5x^2 and 5x"},{"key":"C","text":"4ab and 7ab"},{"key":"D","text":"2x and 2x^2"}]'::jsonb, 'Like terms have identical variable parts. 4ab and 7ab both have the variable ab.'),
    ('3f8c370e-4f71-4d1b-bdf4-2200ea59a3db'::uuid, 'M6.EE.3.1', 'multiple_choice', 'Which value of n is a solution to the inequality n + 3 > 10 ', '[{"key":"A","text":"n = 5"},{"key":"B","text":"n = 7"},{"key":"C","text":"n = 8"},{"key":"D","text":"n = 6"}]'::jsonb, 'C', '8 + 3 = 11 > 10  . Check: 5+3=8, 7+3=10 (not strictly greater), 6+3=9.', 'Which value of n is a solution to the inequality n + 3 > 10?', '[{"key":"A","text":"n = 5"},{"key":"B","text":"n = 7"},{"key":"C","text":"n = 8"},{"key":"D","text":"n = 6"}]'::jsonb, '8 + 3 = 11 > 10 . Check: 5+3=8, 7+3=10 (not strictly greater), 6+3=9.'),
    ('966d9d5f-125c-4d97-bf04-a4fa043b76b7'::uuid, 'M6.EE.3.1', 'multiple_choice', 'Which value of x makes the equation 2x + 5 = 17 true ', '[{"key":"A","text":"x = 4"},{"key":"B","text":"x = 6"},{"key":"C","text":"x = 11"},{"key":"D","text":"x = 7"}]'::jsonb, 'B', '2(6) + 5 = 12 + 5 = 17  . Use substitution to verify.', 'Which value of x makes the equation 2x + 5 = 17 true?', '[{"key":"A","text":"x = 4"},{"key":"B","text":"x = 6"},{"key":"C","text":"x = 11"},{"key":"D","text":"x = 7"}]'::jsonb, '2(6) + 5 = 12 + 5 = 17 . Use substitution to verify.'),
    ('3146a26b-c379-4120-b918-40684f040d9f'::uuid, 'M6.EE.4.1', 'multiple_choice', 'An elevator can hold at most 2,000 pounds. If w = total weight, which inequality represents the safe load ', '[{"key":"A","text":"w > 2000"},{"key":"B","text":"w >= 2000"},{"key":"C","text":"w < 2000"},{"key":"D","text":"w <= 2000"}]'::jsonb, 'D', '''At most 2,000'' means 2,000 or less, so w <= 2000.', 'An elevator can hold at most 2,000 pounds. If w = total weight, which inequality represents the safe load?', '[{"key":"A","text":"w > 2000"},{"key":"B","text":"w >= 2000"},{"key":"C","text":"w < 2000"},{"key":"D","text":"w <= 2000"}]'::jsonb, '''At most 2,000'' means 2,000 or less, so w <= 2000.'),
    ('c5ed474f-bc4f-4148-9592-edad53276dcc'::uuid, 'M6.EE.4.1', 'multiple_choice', 'A roller coaster has a minimum height requirement. Which inequality best represents ''riders must be at least 48 inches tall'' where h = height ', '[{"key":"A","text":"h < 48"},{"key":"B","text":"h > 48"},{"key":"C","text":"h >= 48"},{"key":"D","text":"h <= 48"}]'::jsonb, 'C', '''At least 48'' means 48 or more, so h >= 48.', 'A roller coaster has a minimum height requirement. Which inequality best represents ''riders must be at least 48 inches tall'' where h = height?', '[{"key":"A","text":"h < 48"},{"key":"B","text":"h > 48"},{"key":"C","text":"h >= 48"},{"key":"D","text":"h <= 48"}]'::jsonb, '''At least 48'' means 48 or more, so h >= 48.'),
    ('5cbcccce-1ffb-4577-a6d3-1a62c8a91fbd'::uuid, 'M6.EE.5.1', 'multiple_choice', 'In the relationship ''total earnings depends on hours worked'', which is the independent variable ', '[{"key":"A","text":"Total earnings"},{"key":"B","text":"Hours worked"},{"key":"C","text":"Hourly pay rate"},{"key":"D","text":"Number of days"}]'::jsonb, 'B', 'The independent variable is the input -- what you control. Hours worked determines earnings, so it is independent.', 'In the relationship ''total earnings depends on hours worked'', which is the independent variable?', '[{"key":"A","text":"Total earnings"},{"key":"B","text":"Hours worked"},{"key":"C","text":"Hourly pay rate"},{"key":"D","text":"Number of days"}]'::jsonb, 'The independent variable is the input -- what you control. Hours worked determines earnings, so it is independent.'),
    ('f62048af-75b9-4579-b7f5-3891d0bea086'::uuid, 'M6.EE.5.1', 'multiple_choice', 'A plant''s height (y) grows 2 cm per week (x). Which variable is dependent ', '[{"key":"A","text":"Weeks (x)"},{"key":"B","text":"Height (y)"},{"key":"C","text":"Both are dependent"},{"key":"D","text":"Neither"}]'::jsonb, 'B', 'Height depends on the number of weeks, so height (y) is the dependent variable.', 'A plant''s height (y) grows 2 cm per week (x). Which variable is dependent?', '[{"key":"A","text":"Weeks (x)"},{"key":"B","text":"Height (y)"},{"key":"C","text":"Both are dependent"},{"key":"D","text":"Neither"}]'::jsonb, 'Height depends on the number of weeks, so height (y) is the dependent variable.'),
    ('84d14d9f-b4a0-473c-81be-5df5beb469f7'::uuid, 'M6.GEO.2.1', 'multiple_choice', 'Which net correctly folds into a cube ', '[{"key":"A","text":"A cross shape made of 6 squares"},{"key":"B","text":"A row of 4 squares with 2 attached at one end"},{"key":"C","text":"A T-shape made of 6 squares"},{"key":"D","text":"All of the above"}]'::jsonb, 'D', 'There are 11 valid nets for a cube. Crosses, T-shapes, and L-shapes can all fold into cubes.', 'Which net correctly folds into a cube?', '[{"key":"A","text":"A cross shape made of 6 squares"},{"key":"B","text":"A row of 4 squares with 2 attached at one end"},{"key":"C","text":"A T-shape made of 6 squares"},{"key":"D","text":"All of the above"}]'::jsonb, 'There are 11 valid nets for a cube. Crosses, T-shapes, and L-shapes can all fold into cubes.'),
    ('d89b310b-a522-4e3d-b4d0-4b4596178953'::uuid, 'M6.GEO.2.1', 'multiple_choice', 'A rectangular prism has 6 faces. How many pairs of congruent (identical) faces does it have ', '[{"key":"A","text":"2"},{"key":"B","text":"3"},{"key":"C","text":"6"},{"key":"D","text":"1"}]'::jsonb, 'B', 'A rectangular prism has 3 pairs of congruent faces: top/bottom, front/back, left/right.', 'A rectangular prism has 6 faces. How many pairs of congruent (identical) faces does it have?', '[{"key":"A","text":"2"},{"key":"B","text":"3"},{"key":"C","text":"6"},{"key":"D","text":"1"}]'::jsonb, 'A rectangular prism has 3 pairs of congruent faces: top/bottom, front/back, left/right.'),
    ('f238dda9-5470-4d12-8f15-e4ee78c72c6a'::uuid, 'M6.GEO.3.1', 'multiple_choice', 'A rectangular prism is filled with unit cubes. Each layer has 4 x 3 = 12 cubes and there are 5 layers. What is the volume ', '[{"key":"A","text":"12 cubic units"},{"key":"B","text":"17 cubic units"},{"key":"C","text":"60 cubic units"},{"key":"D","text":"7 cubic units"}]'::jsonb, 'C', 'Volume = base area x height = 12 x 5 = 60 cubic units. This demonstrates V = Bh.', 'A rectangular prism is filled with unit cubes. Each layer has 4 x 3 = 12 cubes and there are 5 layers. What is the volume?', '[{"key":"A","text":"12 cubic units"},{"key":"B","text":"17 cubic units"},{"key":"C","text":"60 cubic units"},{"key":"D","text":"7 cubic units"}]'::jsonb, 'Volume = base area x height = 12 x 5 = 60 cubic units. This demonstrates V = Bh.'),
    ('f0c26925-0703-4ed7-abb7-3dd1dbd5b95d'::uuid, 'M6.GEO.4.2', 'multiple_choice', 'Mia wants to wrap a gift box that is 10 cm x 8 cm x 5 cm. Approximately how many square centimeters of wrapping paper does she need (surface area) ', '[{"key":"A","text":"400 cm^2"},{"key":"B","text":"340 cm^2"},{"key":"C","text":"300 cm^2"},{"key":"D","text":"160 cm^2"}]'::jsonb, 'B', 'SA = 2(10x8) + 2(10x5) + 2(8x5) = 160 + 100 + 80 = 340 cm^2.', 'Mia wants to wrap a gift box that is 10 cm x 8 cm x 5 cm. Approximately how many square centimeters of wrapping paper does she need (surface area)?', '[{"key":"A","text":"400 cm^2"},{"key":"B","text":"340 cm^2"},{"key":"C","text":"300 cm^2"},{"key":"D","text":"160 cm^2"}]'::jsonb, 'SA = 2(10x8) + 2(10x5) + 2(8x5) = 160 + 100 + 80 = 340 cm^2.'),
    ('398bf61a-25a7-433d-bd1e-81844a291cf4'::uuid, 'M6.NS.2.1', 'multiple_choice', 'Which expression represents the question: ''How many 1/3-cup servings are in 2 cups ''', '[{"key":"A","text":"2 x 1/3"},{"key":"B","text":"2 / 1/3"},{"key":"C","text":"1/3 / 2"},{"key":"D","text":"2 - 1/3"}]'::jsonb, 'B', 'Dividing the total by the serving size gives the number of servings: 2 / 1/3 = 6.', 'Which expression represents the question: ''How many 1/3-cup servings are in 2 cups ''?', '[{"key":"A","text":"2 x 1/3"},{"key":"B","text":"2 / 1/3"},{"key":"C","text":"1/3 / 2"},{"key":"D","text":"2 - 1/3"}]'::jsonb, 'Dividing the total by the serving size gives the number of servings: 2 / 1/3 = 6.'),
    ('cc4dc9f7-4dca-4431-a135-4bb783c689b1'::uuid, 'M6.NS.2.1', 'multiple_choice', 'A recipe calls for 1/2 cup of oil. Marcos only has a 1/8 cup measuring cup. Which expression gives the number of times he must fill it ', '[{"key":"A","text":"1/2 x 1/8"},{"key":"B","text":"1/8 / 1/2"},{"key":"C","text":"1/2 / 1/8"},{"key":"D","text":"1/2 + 1/8"}]'::jsonb, 'C', '1/2 / 1/8 = 1/2 x 8 = 4. He fills the 1/8-cup measure 4 times.', 'A recipe calls for 1/2 cup of oil. Marcos only has a 1/8 cup measuring cup. Which expression gives the number of times he must fill it?', '[{"key":"A","text":"1/2 x 1/8"},{"key":"B","text":"1/8 / 1/2"},{"key":"C","text":"1/2 / 1/8"},{"key":"D","text":"1/2 + 1/8"}]'::jsonb, '1/2 / 1/8 = 1/2 x 8 = 4. He fills the 1/8-cup measure 4 times.'),
    ('d59e9723-3806-4bbb-b432-379c9ae5ae30'::uuid, 'M6.NS.2.1', 'multiple_choice', 'On a number line, which model shows 3/4 / 1/4 ', '[{"key":"A","text":"Starting at 0, jumping 1/4 three times"},{"key":"B","text":"Starting at 3/4, going back 1/4 once"},{"key":"C","text":"Starting at 0 and jumping 3/4 four times"},{"key":"D","text":"Dividing the segment from 0 to 3/4 into equal parts of 1/4 and counting them"}]'::jsonb, 'D', 'Fraction division 3/4 / 1/4 asks: how many 1/4-size pieces fit in 3/4  Answer: 3.', 'On a number line, which model shows 3/4 / 1/4?', '[{"key":"A","text":"Starting at 0, jumping 1/4 three times"},{"key":"B","text":"Starting at 3/4, going back 1/4 once"},{"key":"C","text":"Starting at 0 and jumping 3/4 four times"},{"key":"D","text":"Dividing the segment from 0 to 3/4 into equal parts of 1/4 and counting them"}]'::jsonb, 'Fraction division 3/4 / 1/4 asks: how many 1/4-size pieces fit in 3/4 Answer: 3.'),
    ('2ece3a90-b00b-4b19-ae45-6fb61aab7571'::uuid, 'M6.NS.4.1', 'multiple_choice', 'Which situation is best represented by the number +$35 ', '[{"key":"A","text":"Spending $35 at a store"},{"key":"B","text":"Owing $35 on a bill"},{"key":"C","text":"Earning $35 from babysitting"},{"key":"D","text":"Losing $35 from a wallet"}]'::jsonb, 'C', 'Positive values represent gains or increases; earning $35 is a gain.', 'Which situation is best represented by the number +$35?', '[{"key":"A","text":"Spending $35 at a store"},{"key":"B","text":"Owing $35 on a bill"},{"key":"C","text":"Earning $35 from babysitting"},{"key":"D","text":"Losing $35 from a wallet"}]'::jsonb, 'Positive values represent gains or increases; earning $35 is a gain.'),
    ('a36b625c-f582-4582-aa52-fb1d52dd5a4b'::uuid, 'M6.NS.4.1', 'multiple_choice', 'A city''s elevation is -48 feet. Which statement correctly interprets this value ', '[{"key":"A","text":"The city is 48 feet above sea level"},{"key":"B","text":"The city is 48 feet below sea level"},{"key":"C","text":"The city is at sea level"},{"key":"D","text":"The city is 48 miles from the coast"}]'::jsonb, 'B', 'Negative elevation means below sea level; -48 feet means 48 feet below sea level.', 'A city''s elevation is -48 feet. Which statement correctly interprets this value?', '[{"key":"A","text":"The city is 48 feet above sea level"},{"key":"B","text":"The city is 48 feet below sea level"},{"key":"C","text":"The city is at sea level"},{"key":"D","text":"The city is 48 miles from the coast"}]'::jsonb, 'Negative elevation means below sea level; -48 feet means 48 feet below sea level.'),
    ('0e3f26e7-7c76-4546-8fb7-d1bb24e28292'::uuid, 'M6.NS.4.2', 'multiple_choice', 'What is the opposite of -15 ', '[{"key":"A","text":"0"},{"key":"B","text":"15"},{"key":"C","text":"-(-15) which equals -15"},{"key":"D","text":"1/15"}]'::jsonb, 'B', 'The opposite of a number is its reflection over 0 on the number line. Opposite of -15 is +15.', 'What is the opposite of -15?', '[{"key":"A","text":"0"},{"key":"B","text":"15"},{"key":"C","text":"-(-15) which equals -15"},{"key":"D","text":"1/15"}]'::jsonb, 'The opposite of a number is its reflection over 0 on the number line. Opposite of -15 is +15.'),
    ('40969ff7-0930-40e6-b31d-ca0687d47185'::uuid, 'M6.NS.4.2', 'multiple_choice', 'Which two numbers on a number line are both 7 units from zero ', '[{"key":"A","text":"7 and 14"},{"key":"B","text":"7 and 0"},{"key":"C","text":"7 and -7"},{"key":"D","text":"0 and -7"}]'::jsonb, 'C', 'Opposites are equidistant from zero; both 7 and -7 are exactly 7 units from 0.', 'Which two numbers on a number line are both 7 units from zero?', '[{"key":"A","text":"7 and 14"},{"key":"B","text":"7 and 0"},{"key":"C","text":"7 and -7"},{"key":"D","text":"0 and -7"}]'::jsonb, 'Opposites are equidistant from zero; both 7 and -7 are exactly 7 units from 0.'),
    ('1c68a49f-3f59-4caa-b2a3-93489e254060'::uuid, 'M6.RP.1.1', 'multiple_choice', 'A class has 12 boys and 16 girls. Which correctly expresses the ratio of boys to the total number of students ', '[{"key":"A","text":"12:16"},{"key":"B","text":"16:12"},{"key":"C","text":"12:28"},{"key":"D","text":"28:12"}]'::jsonb, 'C', 'Ratio of boys to total = 12 : (12 + 16) = 12 : 28.', 'A class has 12 boys and 16 girls. Which correctly expresses the ratio of boys to the total number of students?', '[{"key":"A","text":"12:16"},{"key":"B","text":"16:12"},{"key":"C","text":"12:28"},{"key":"D","text":"28:12"}]'::jsonb, 'Ratio of boys to total = 12 : (12 + 16) = 12 : 28.'),
    ('c25c4ff4-9035-4226-ba28-76ef19574b3d'::uuid, 'M6.RP.1.1', 'multiple_choice', 'Which of the following is NOT an equivalent way to write the ratio 3 to 5 ', '[{"key":"A","text":"3:5"},{"key":"B","text":"3/5"},{"key":"C","text":"5/3"},{"key":"D","text":"3 to 5"}]'::jsonb, 'C', '3 to 5, 3:5, and 3/5 are all equivalent. 5/3 reverses the relationship.', 'Which of the following is NOT an equivalent way to write the ratio 3 to 5?', '[{"key":"A","text":"3:5"},{"key":"B","text":"3/5"},{"key":"C","text":"5/3"},{"key":"D","text":"3 to 5"}]'::jsonb, '3 to 5, 3:5, and 3/5 are all equivalent. 5/3 reverses the relationship.'),
    ('5814a4c0-0b23-4518-96fe-de63212aca39'::uuid, 'M6.RP.1.2', 'multiple_choice', 'Which statement BEST defines a unit rate ', '[{"key":"A","text":"A ratio that compares two quantities with the same units"},{"key":"B","text":"A rate with a denominator of 1"},{"key":"C","text":"Any fraction less than 1"},{"key":"D","text":"A rate that equals exactly 100"}]'::jsonb, 'B', 'A unit rate expresses the value per 1 unit of the second quantity (denominator = 1).', 'Which statement BEST defines a unit rate?', '[{"key":"A","text":"A ratio that compares two quantities with the same units"},{"key":"B","text":"A rate with a denominator of 1"},{"key":"C","text":"Any fraction less than 1"},{"key":"D","text":"A rate that equals exactly 100"}]'::jsonb, 'A unit rate expresses the value per 1 unit of the second quantity (denominator = 1).'),
    ('57124bd5-f00e-4c62-ac9f-971d292587d7'::uuid, 'M6.RP.3.1', 'multiple_choice', 'Which correctly expresses 45% as a rate per 100 ', '[{"key":"A","text":"45/10"},{"key":"B","text":"45/1000"},{"key":"C","text":"45/100"},{"key":"D","text":"4.5/100"}]'::jsonb, 'C', 'Percent means ''per hundred,'' so 45% = 45 per 100 = 45/100.', 'Which correctly expresses 45% as a rate per 100?', '[{"key":"A","text":"45/10"},{"key":"B","text":"45/1000"},{"key":"C","text":"45/100"},{"key":"D","text":"4.5/100"}]'::jsonb, 'Percent means ''per hundred,'' so 45% = 45 per 100 = 45/100.'),
    ('5c4f052d-b32e-45b2-8f98-8e242bef3449'::uuid, 'M6.RP.3.1', 'multiple_choice', 'A store says 3 out of every 100 items are returned. What percent of items are returned ', '[{"key":"A","text":"0.03%"},{"key":"B","text":"3%"},{"key":"C","text":"30%"},{"key":"D","text":"300%"}]'::jsonb, 'B', '3 out of 100 = 3/100 = 3%.', 'A store says 3 out of every 100 items are returned. What percent of items are returned?', '[{"key":"A","text":"0.03%"},{"key":"B","text":"3%"},{"key":"C","text":"30%"},{"key":"D","text":"300%"}]'::jsonb, '3 out of 100 = 3/100 = 3%.'),
    ('6387be34-849b-49b0-b391-e5ddee875bcb'::uuid, 'M6.SP.1.1', 'multiple_choice', 'Which of the following is a statistical question ', '[{"key":"A","text":"How many students are in Ms. Taylor''''s class today "},{"key":"B","text":"What is 8 x 7 "},{"key":"C","text":"How many minutes do 6th graders spend on homework each night "},{"key":"D","text":"What is the capital of North Carolina "}]'::jsonb, 'C', 'A statistical question anticipates variability across individuals -- different students will have different homework times.', 'Which of the following is a statistical question?', '[{"key":"A","text":"How many students are in Ms. Taylor''''s class today"},{"key":"B","text":"What is 8 x 7"},{"key":"C","text":"How many minutes do 6th graders spend on homework each night"},{"key":"D","text":"What is the capital of North Carolina"}]'::jsonb, 'A statistical question anticipates variability across individuals -- different students will have different homework times.'),
    ('81a06b69-e403-4f04-ba95-4bcd7bf2720b'::uuid, 'M6.SP.1.2', 'multiple_choice', 'A data set shows test scores: 72, 85, 90, 68, 91, 85, 77. What makes this a data SET rather than a single data point ', '[{"key":"A","text":"The values are all different"},{"key":"B","text":"It contains multiple values from multiple observations"},{"key":"C","text":"All values are greater than 50"},{"key":"D","text":"The values are whole numbers"}]'::jsonb, 'B', 'A data set is a collection of values gathered from multiple observations or individuals.', 'A data set shows test scores: 72, 85, 90, 68, 91, 85, 77. What makes this a data SET rather than a single data point?', '[{"key":"A","text":"The values are all different"},{"key":"B","text":"It contains multiple values from multiple observations"},{"key":"C","text":"All values are greater than 50"},{"key":"D","text":"The values are whole numbers"}]'::jsonb, 'A data set is a collection of values gathered from multiple observations or individuals.'),
    ('5a9025c6-eddb-4937-816f-7ea50e079529'::uuid, 'M6.SP.2.1', 'multiple_choice', 'Which type of display is BEST suited for showing the frequency of data grouped into intervals (e.g., ages 10-12, 13-15) ', '[{"key":"A","text":"Dot plot"},{"key":"B","text":"Box plot"},{"key":"C","text":"Histogram"},{"key":"D","text":"Stem-and-leaf plot"}]'::jsonb, 'C', 'Histograms display data grouped into intervals (bins) with bar heights showing frequency.', 'Which type of display is BEST suited for showing the frequency of data grouped into intervals (e.g., ages 10-12, 13-15)?', '[{"key":"A","text":"Dot plot"},{"key":"B","text":"Box plot"},{"key":"C","text":"Histogram"},{"key":"D","text":"Stem-and-leaf plot"}]'::jsonb, 'Histograms display data grouped into intervals (bins) with bar heights showing frequency.'),
    ('95a88626-1bcc-41b9-94eb-b7cf3e64668c'::uuid, 'M6.SP.4.1', 'multiple_choice', 'A histogram shows most data clustered on the right with a long tail to the left. This distribution is best described as:', '[{"key":"A","text":"Symmetric"},{"key":"B","text":"Skewed right"},{"key":"C","text":"Skewed left"},{"key":"D","text":"Uniform"}]'::jsonb, 'C', 'Skewed left (negatively skewed) means most data is on the right with the tail extending to the left.', 'A histogram shows most data clustered on the right with a long tail to the left. This distribution is best described as:', '[{"key":"A","text":"Symmetric"},{"key":"B","text":"Skewed right"},{"key":"C","text":"Skewed left"},{"key":"D","text":"Uniform"}]'::jsonb, 'Skewed left (negatively skewed) means most data is on the right with the tail extending to the left.'),
    ('e508b24a-6785-4e23-ab96-12b784a90a76'::uuid, 'M6.SP.4.2', 'multiple_choice', 'A data set has values: 12, 14, 15, 13, 11, 14, 87. What is likely the outlier and what measure of center does it most affect ', '[{"key":"A","text":"87 is an outlier; it greatly affects the mean"},{"key":"B","text":"87 is an outlier; it greatly affects the median"},{"key":"C","text":"11 is an outlier; it affects the mode"},{"key":"D","text":"There is no outlier"}]'::jsonb, 'A', '87 is far from the cluster 11-15; it is an outlier. Outliers have a large impact on the mean but minimal impact on the median.', 'A data set has values: 12, 14, 15, 13, 11, 14, 87. What is likely the outlier and what measure of center does it most affect?', '[{"key":"A","text":"87 is an outlier; it greatly affects the mean"},{"key":"B","text":"87 is an outlier; it greatly affects the median"},{"key":"C","text":"11 is an outlier; it affects the mode"},{"key":"D","text":"There is no outlier"}]'::jsonb, '87 is far from the cluster 11-15; it is an outlier. Outliers have a large impact on the mean but minimal impact on the median.'),
    ('04984eaa-b3dd-497e-b39d-6d0534fcfd04'::uuid, 'M6.SP.5.1', 'multiple_choice', 'A researcher collects the ages of 150 people at a community center. Which statement about this data set is appropriate ', '[{"key":"A","text":"The data has 1 observation"},{"key":"B","text":"The data was collected in a context where age varies among individuals"},{"key":"C","text":"The data has no variability"},{"key":"D","text":"The data can only be displayed in a bar graph"}]'::jsonb, 'B', 'Summarizing a data set in context begins by noting that the data varies across the 150 individuals surveyed.', 'A researcher collects the ages of 150 people at a community center. Which statement about this data set is appropriate?', '[{"key":"A","text":"The data has 1 observation"},{"key":"B","text":"The data was collected in a context where age varies among individuals"},{"key":"C","text":"The data has no variability"},{"key":"D","text":"The data can only be displayed in a bar graph"}]'::jsonb, 'Summarizing a data set in context begins by noting that the data varies across the 150 individuals surveyed.'),
    ('606c8082-2025-4982-a376-eed6d95c4cd2'::uuid, 'M6.SP.5.2', 'multiple_choice', 'A data set is symmetric and bell-shaped with no outliers. Which measure of center is MOST appropriate ', '[{"key":"A","text":"Median only"},{"key":"B","text":"Mode only"},{"key":"C","text":"Mean (or median -- they are approximately equal)"},{"key":"D","text":"Range"}]'::jsonb, 'C', 'For symmetric distributions with no outliers, mean and median are approximately equal -- either is appropriate. The mean is often preferred.', 'A data set is symmetric and bell-shaped with no outliers. Which measure of center is MOST appropriate?', '[{"key":"A","text":"Median only"},{"key":"B","text":"Mode only"},{"key":"C","text":"Mean (or median -- they are approximately equal)"},{"key":"D","text":"Range"}]'::jsonb, 'For symmetric distributions with no outliers, mean and median are approximately equal -- either is appropriate. The mean is often preferred.'),
    ('90b231df-485f-476c-aae3-188fe002fda3'::uuid, 'M6.SP.5.2', 'multiple_choice', 'A data set is heavily skewed right (with a few very large values). Which measure of center BEST represents the typical value ', '[{"key":"A","text":"Mean"},{"key":"B","text":"Median"},{"key":"C","text":"Mode"},{"key":"D","text":"Range"}]'::jsonb, 'B', 'When data is skewed, the median is less affected by extreme values than the mean and better represents the typical observation.', 'A data set is heavily skewed right (with a few very large values). Which measure of center BEST represents the typical value?', '[{"key":"A","text":"Mean"},{"key":"B","text":"Median"},{"key":"C","text":"Mode"},{"key":"D","text":"Range"}]'::jsonb, 'When data is skewed, the median is less affected by extreme values than the mean and better represents the typical observation.')
)
SELECT
  sq.id AS static_question_id,
  sq.concept_id AS lesson_number,
  sq.question_text = e.after_question_text AS prompt_matches_expected_normalization,
  sq.options = e.after_options AS options_match_expected_normalization,
  sq.explanation = e.after_explanation AS explanation_matches_expected_normalization,
  sq.correct_answer = e.correct_answer AS correct_answer_unchanged,
  sq.question_type = e.question_type AS question_type_unchanged,
  sq.is_active = TRUE AS remains_active,
  COALESCE(sq.is_verified, FALSE) = FALSE AS remains_unverified,
  md5(
    jsonb_build_object(
      'static_question_id', sq.id,
      'lesson_number', sq.concept_id,
      'question_type', sq.question_type,
      'question_text', sq.question_text,
      'options', sq.options,
      'correct_answer', sq.correct_answer,
      'explanation', sq.explanation,
      'difficulty', sq.difficulty,
      'is_active', sq.is_active,
      'is_verified', sq.is_verified
    )::text
  ) AS live_postchange_md5
FROM public.static_questions AS sq
JOIN expected AS e ON e.id = sq.id
ORDER BY sq.concept_id, sq.id;
